### ISSUE TITLE
Flakiness?

### ISSUE THREAD

**Issue by tommythorn** [xesscorp/XSTOOLs#11]
I suppose this could be my issue somehow, but I find that I run into this frequently without any rhyme or reason:

```
[tommy@somehost EchoTestVerilog]$ python EchoTestVerilog.py
Traceback (most recent call last):
  File "EchoTestVerilog.py", line 6, in <module>
    comm = XsComm(xsusb_id=USB_ID, module_id=255)
  File "/usr/lib/python2.6/site-packages/XsTools-0.1.26-py2.6.egg/xstools/xscomm.py", line 61, in __init__
    self._memio = XsMemIo(xsusb_id=xsusb_id, module_id=module_id, xsjtag=xsjtag)
  File "/usr/lib/python2.6/site-packages/XsTools-0.1.26-py2.6.egg/xstools/xsmemio.py", line 62, in __init__
    assert self.address_width != 0
AssertionError
```

whereas successful runs would look like

```
[tommy@somehost EchoTestVerilog]$ xsload.py --fpga EchoTestVerilog_lx25.bit  && python EchoTestVerilog.py
Success: Bitstream EchoTestVerilog_lx25.bit downloaded into XuLA2-LX25 !
Exception AttributeError: "'NoneType' object has no attribute 'copy'" in <bound method Device.__del__ of <usb.core.Device object at 0x8684a4c>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'libusb_unref_device'" in <bound method _Device.__del__ of <usb.backend.libusb1._Device object at 0x8684a6c>> ignored
(3, 8)
A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
```

I see this both on Linux and Mac OS X.

**Comment by xesscorp** [comment]
I've also seen this behavior. It's caused by the failure of the USB-to-JTAG link so the Python program isn't able to fetch the parameters describing the interface from the FPGA. The problem has something to do with how the FPGA circuitry is synthesized. I can make the problem go away by making the HDL synthesizer prioritize area over speed (or vice-versa), by turning register duplication on or off, by increasing the synthesizer effort, etc. There's no consistent synthesizer settings that solve the problem, and if I add circuitry to debug it then the problem goes away. I've tried looking at the synthesizer output, but that's such a thicket that I can't make any headway.

So no, this is not your issue. But I also don't have a solution for it.
