### ISSUE TITLE
xstest.py - Ubuntu 11.10 

### ISSUE THREAD

**Issue by JavierGr** [xesscorp/XSTOOLs#5]
When running:

xstest.py -u0

I get:

Traceback (most recent call last):
  File "/usr/local/bin/xstest.py", line 66, in <module>
    xs_board = XSBOARD.XsBoard.get_xsboard(args.usb)
  File "/usr/local/lib/python2.7/dist-packages/xstools/xsboard.py", line 56, in get_xsboard
  File "/usr/local/lib/python2.7/dist-packages/xstools/xsboard.py", line 98, in is_connected
  File "/usr/local/lib/python2.7/dist-packages/xstools/xilfpga.py", line 76, in is_connected
  File "/usr/local/lib/python2.7/dist-packages/xstools/xilfpga.py", line 71, in get_idcode
  File "/usr/local/lib/python2.7/dist-packages/xstools/xsjtag.py", line 267, in load_ir_then_dr
  File "/usr/local/lib/python2.7/dist-packages/xstools/xsjtag.py", line 105, in shift_tdi
  File "/usr/local/lib/python2.7/dist-packages/xstools/xsjtag.py", line 218, in flush
  File "/usr/local/lib/python2.7/dist-packages/xstools/xsjtag.py", line 230, in flush
  File "/usr/local/lib/python2.7/dist-packages/xstools/xsusb.py", line 205, in write
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 626, in write
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 532, in bulk_write
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 631, in __write
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 403, in _check
usb.core.USBError: [Errno 32] Pipe error

then led on the Xula2 turns off and xstest.py does not recognize the board until unplugged and plugged again.

running it with sudo:

Traceback (most recent call last):
  File "/usr/local/bin/xstest.py", line 66, in <module>
    xs_board = XSBOARD.XsBoard.get_xsboard(args.usb)
  File "/usr/local/lib/python2.7/dist-packages/xstools/xsboard.py", line 56, in get_xsboard
    if xsboard.is_connected():
  File "/usr/local/lib/python2.7/dist-packages/xstools/xsboard.py", line 98, in is_connected
    return self.fpga.is_connected()
  File "/usr/local/lib/python2.7/dist-packages/xstools/xilfpga.py", line 76, in is_connected
    return self.get_idcode().head(28) == self._IDCODE.head(28)
  File "/usr/local/lib/python2.7/dist-packages/xstools/xilfpga.py", line 71, in get_idcode
    return self.xsjtag.load_ir_then_dr(instruction=self._IDCODE_INSTR, data=None, num_return_bits=IDCODE_LENGTH)
  File "/usr/local/lib/python2.7/dist-packages/xstools/xsjtag.py", line 267, in load_ir_then_dr
    self.shift_tdi(tdi=instruction, do_exit_shift=True)
  File "/usr/local/lib/python2.7/dist-packages/xstools/xsjtag.py", line 105, in shift_tdi
    self.flush()  # Flush everything to the JTAG port.
  File "/usr/local/lib/python2.7/dist-packages/xstools/xsjtag.py", line 218, in flush
    self.flush()
  File "/usr/local/lib/python2.7/dist-packages/xstools/xsjtag.py", line 230, in flush
    self._xsusb.write(buffer)
  File "/usr/local/lib/python2.7/dist-packages/xstools/xsusb.py", line 205, in write
    bytes, 0, time_out) \
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 626, in write
    self.__get_timeout(timeout)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 532, in bulk_write
    timeout)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 631, in __write
    _check(retval)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 403, in _check
    raise USBError(_str_error[ret], ret, _libusb_errno[ret])
usb.core.USBError: [Errno 32] Pipe error

and again the led turns off, etc.

I'm pretty sure the problem its not the board: gxstest in windows xp worked;

**Comment by xesscorp** [comment]
You will need to upgrade the firmware in your XuLA board in order to use 
the python version of XSTOOLs. Unplug and replug your XuLA and then 
issue the command "python xsusbprg.py" and the new firmware will be 
loaded. Then try xstest.py again and see if the problem is still present.

> When running:
> 
> xstest.py -u0
> 
> I get:
> 
> Traceback (most recent call last):
> File "/usr/local/bin/xstest.py", line 66, in
> xs_board = XSBOARD.XsBoard.get_xsboard(args.usb)
> File "/usr/local/lib/python2.7/dist-packages/xstools/xsboard.py", line 
> 56, in get_xsboard
> File "/usr/local/lib/python2.7/dist-packages/xstools/xsboard.py", line 
> 98, in is_connected
> File "/usr/local/lib/python2.7/dist-packages/xstools/xilfpga.py", line 
> 76, in is_connected
> File "/usr/local/lib/python2.7/dist-packages/xstools/xilfpga.py", line 
> 71, in get_idcode
> File "/usr/local/lib/python2.7/dist-packages/xstools/xsjtag.py", line 
> 267, in load_ir_then_dr
> File "/usr/local/lib/python2.7/dist-packages/xstools/xsjtag.py", line 
> 105, in shift_tdi
> File "/usr/local/lib/python2.7/dist-packages/xstools/xsjtag.py", line 
> 218, in flush
> File "/usr/local/lib/python2.7/dist-packages/xstools/xsjtag.py", line 
> 230, in flush
> File "/usr/local/lib/python2.7/dist-packages/xstools/xsusb.py", line 
> 205, in write
> File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 626, 
> in write
> File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", 
> line 532, in bulk_write
> File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", 
> line 631, in __write
> File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", 
> line 403, in _check
> usb.core.USBError: [Errno 32] Pipe error
> 
> then led on the Xula2 turns off and xstest.py does not recognize the 
> board until unplugged and plugged again.
> 
> running it with sudo:
> 
> Traceback (most recent call last):
> File "/usr/local/bin/xstest.py", line 66, in
> xs_board = XSBOARD.XsBoard.get_xsboard(args.usb)
> File "/usr/local/lib/python2.7/dist-packages/xstools/xsboard.py", line 
> 56, in get_xsboard
> if xsboard.is_connected():
> File "/usr/local/lib/python2.7/dist-packages/xstools/xsboard.py", line 
> 98, in is_connected
> return self.fpga.is_connected()
> File "/usr/local/lib/python2.7/dist-packages/xstools/xilfpga.py", line 
> 76, in is_connected
> return self.get_idcode().head(28) == self._IDCODE.head(28)
> File "/usr/local/lib/python2.7/dist-packages/xstools/xilfpga.py", line 
> 71, in get_idcode
> return self.xsjtag.load_ir_then_dr(instruction=self._IDCODE_INSTR, 
> data=None, num_return_bits=IDCODE_LENGTH)
> File "/usr/local/lib/python2.7/dist-packages/xstools/xsjtag.py", line 
> 267, in load_ir_then_dr
> self.shift_tdi(tdi=instruction, do_exit_shift=True)
> File "/usr/local/lib/python2.7/dist-packages/xstools/xsjtag.py", line 
> 105, in shift_tdi
> self.flush() # Flush everything to the JTAG port.
> File "/usr/local/lib/python2.7/dist-packages/xstools/xsjtag.py", line 
> 218, in flush
> self.flush()
> File "/usr/local/lib/python2.7/dist-packages/xstools/xsjtag.py", line 
> 230, in flush
> self._xsusb.write(buffer)
> File "/usr/local/lib/python2.7/dist-packages/xstools/xsusb.py", line 
> 205, in write
> bytes, 0, time_out) \
> File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 626, 
> in write
> self.__get_timeout(timeout)
> File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", 
> line 532, in bulk_write
> timeout)
> File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", 
> line 631, in __write
> _check(retval)
> File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", 
> line 403, in _check
> raise USBError(_str_error[ret], ret, _libusb_errno[ret])
> usb.core.USBError: [Errno 32] Pipe error
> 
> and again the led turns off, etc.
> 
> I'm pretty sure the problem its not the board: gxstest in windows xp 
> worked;
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/xesscorp/XSTOOLs/issues/5.

## 

---

Dave Vandenbout / XESS Corp.
2608 Sweetgum Drive
Apex NC 27539-8851
USA
/devb@xess.com/

## /www.xess.com/

**Comment by JavierGr** [comment]
It worked. Thanks!.

**Comment by xesscorp** [comment]
On 07/26/2013 8:55 AM, JavierGr wrote:

> It worked. Thanks!.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/xesscorp/XSTOOLs/issues/5#issuecomment-21618728.

No problem! Let me know if there are any further difficulties.

## 

---

Dave Vandenbout / XESS Corp.
2608 Sweetgum Drive
Apex NC 27539-8851
USA
/devb@xess.com/

## /www.xess.com/
